version: "2"
run:
  concurrency: 4
  timeout: 10m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
